### ISSUE TITLE
iconv-lite cant find

### ISSUE THREAD

**Issue by mr-m0nst3r** [AntSwordProject/antSword#149]
```shell
Uncaught Exception:
Error: Cannot find module 'iconv-lite'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/Applications/AntSword.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/michael/tools/antSword/modules/request.js:9:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

这是antloader给的提示
---

## 报告 Bug

- [ x] 我使用的操作系统是 ***macOS*** 10+
- [ ] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [ ] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [ x] 我使用的是 64 位操作系统

### Bug 详细描述
```
Uncaught Exception:
Error: Cannot find module 'iconv-lite'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/Applications/AntSword.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/michael/tools/antSword/modules/request.js:9:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
```

---
![image](https://user-images.githubusercontent.com/38524240/56223165-d4564180-609f-11e9-9387-e6a107d21c69.png)

**Comment by mr-m0nst3r** [comment]
maybe conflit with `nvm`, uninstalled nvm and reinstalled node fixed this.
