### ISSUE TITLE
文件下载失败JSP+BASE64+LINUX

### ISSUE THREAD

**Issue by supermisscat** [AntSwordProject/antSword#178]
下载任何文件都出错
![image](https://user-images.githubusercontent.com/16932404/58221833-7bd12e80-7d46-11e9-871c-8ba20a9be970.png)
然后会下载到一个5k的文件，里面是服务器response，报错了。
`tml>
<head>
    <title>系统运行异常500错误</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>

<body>
<div style="position:absolute; top:50%; left:50%; margin-top:-120px; margin-left:-290px; width:580px; height:240px;border:1px dashed #ccc;">
    <table cellpadding="0" cellspacing="0" width="450">

        <tr>
            <td style="line-height:24px; font-size:14px;" valign="top">
                2019-05-23 10:33:35  系统运行异常。<br><br>
                response.getWriter() called after response.getOutputStream()</td>
        </tr>

        <tr style="display: none" id="errorid">
            <td>
                java.lang.IllegalStateException: response.getWriter() called after response.getOutputStream()
	at com.opensymphony.module.sitemesh.filter.Buffer.getWriter(Buffer.java:55)
	at com.opensymphony.module.sitemesh.filter.PageResponseWrapper$3.activateDestination(PageResponseWrapper.java:79)
	at com.opensymphony.module.sitemesh.filter.RoutablePrintWriter.getDestination(RoutablePrintWriter.java:38)
	at com.opensymphony.module.sitemesh.filter.RoutablePrintWriter.write(RoutablePrintWriter.java:144)
	at org.apache.jasper.runtime.JspWriterImpl.flushBuffer(JspWriterImpl.java:119)
	at org.apache.jasper.runtime.PageContextImpl.release(PageContextImpl.java:190)
	at org.apache.jasper.runtime.JspFactoryImpl.internalReleasePageContext(JspFactoryImpl.java:123)
	at org.apache.jasper.runtime.JspFactoryImpl.releasePageContext(JspFactoryImpl.java:80)
	at org.apache.jsp.xx.xx.xx.xx.muma_jsp._jspService(muma_jsp.java:474)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:432)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:83)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.vetech.core.modules.antisamy.AntiSamyFilter.doFilter(AntiSamyFilter.java:58)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:108)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:224)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:169)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:168)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:927)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:987)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:579)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:307)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

</td>
        </tr>
    </table>
</div>
</body>
</html`

tomcat7
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by Medicean** [comment]
未能复现你所提到的问题

<img width="1040" alt="issue-178" src="https://user-images.githubusercontent.com/6082020/58223903-226cfd80-7d4e-11e9-98a8-ecec709aa9c4.png">

<img width="544" alt="issue-178_2" src="https://user-images.githubusercontent.com/6082020/58223953-5fd18b00-7d4e-11e9-9683-8be83b7dd085.png">

**Comment by supermisscat** [comment]
> 未能复现你所提到的问题
> 
> <img alt="issue-178" width="1040" src="https://user-images.githubusercontent.com/6082020/58223903-226cfd80-7d4e-11e9-98a8-ecec709aa9c4.png">
> 
> <img alt="issue-178_2" width="544" src="https://user-images.githubusercontent.com/6082020/58223953-5fd18b00-7d4e-11e9-9683-8be83b7dd085.png">
> 
> 就你提供的报错信息来看，`response.getWriter` 这个方法在 [jsp_custom_script_for_mysql.jsp](https://raw.githubusercontent.com/AntSwordProject/antSword/master/shells/jsp_custom_script_for_mysql.jsp) 这个文件里都没找到，或许你用的 webshell 并未实现蚁剑的 CUSTOM 接口吧

好吧 可能又是奇葩环境。其他功能是正常的，就下载。。

**Comment by yzddmr6** [comment]
试试如果用default模式能下载吗
