### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by huitc** [AntSwordProject/antSword#189]
我使用的操作系统是 ***Windows*** 10+
我使用的是 64 位操作系统

```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
TypeError: unsupported proxy protocol: "undefined"
    at mapOptsToProxy (C:\Users\test\Documents\test\antSword-2.1.3\node_modules\proxy-agent\index.js:112:11)
    at new ProxyAgent (C:\Users\test\Documents\test\antSword-2.1.3\node_modules\proxy-agent\index.js:150:17)
    at ProxyAgent (C:\Users\test\Documents\test\antSword-2.1.3\node_modules\proxy-agent\index.js:145:45)
    at Request.proxy (C:\Users\test\Documents\test\antSword-2.1.3\node_modules\superagent-proxy\index.js:71:15)
    at Request.onRequest (C:\Users\test\Documents\test\antSword-2.1.3\modules\request.js:139:10)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\test\Documents\test\AntSword-Loader-v4.0.3-win32-x64\resources\electron.asar\browser\api\web-contents.js:334:13)
    at WebContents.emit (events.js:182:13)

[確定]
```

**Comment by Medicean** [comment]
你的代理配置是怎么配的？

**Comment by huitc** [comment]
tor那個
