### ISSUE TITLE
AntSword-Loader安装存在问题

### ISSUE THREAD

**Issue by An0th3r** [AntSwordProject/antSword#204]
- [ ] 我确定这是蚁剑本身的一个 Bug，我并不是在询问如何使用蚁剑
- [+ ] 我确定已经将蚁剑升级至[软件发布页面](https://github.com/AntSwordProject/AntSword/releases)中的**最新版**
- [ ] 我已经阅读过蚁剑的开发文档，并且尝试过自己通过Google等方式解决问题
- [ ] 这是一个新功能的建议
- [+] 我查阅了文档没找到解决方案，所以来询问如何使用蚁剑

---

## 报告 Bug

- [ ] 我使用的操作系统是 ***macOS*** 10+
- [+] 我使用的操作系统是 ***Debian/Ubuntu*** GNU/Linux
- [ ] 我使用的操作系统是 ***Fedora*** GNU/Linux
- [ ] 我使用的操作系统是 ***Arch*** GNU/Linux
- [ ] 我使用的操作系统是 ***Other*** GNU/Linux
- [ ] 我使用的操作系统是 ***Windows*** 10+

---

- [ ] 我使用的是 32 位操作系统
- [+] 我使用的是 64 位操作系统

### Bug 详细描述

通过AntSword-Loader安装AntSword，在kali上无法最小化，最小化后dock上的图标消失，但AntSword进程不会终止
---

## 新功能建议

- [ ] 我确定我所提的新功能不在[待做事项](https://github.com/AntSwordProject/AntSword/blob/master/CHANGELOG.md#待做事项)内，也不在issue列表
- [ ] 我确定我所提出的新功能是为了方便在网站管理，而不是用于非法用途

### 新功能描述

---

### shell 连接 Bug

1. 服务端操作系统

2. 服务端shell代码

3. 服务端环境配置

4. 客户端连接配置

**Comment by davie89** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.16.2
4 verbose stack Error: Invalid version: "2.1.4.1"
4 verbose stack     at Object.fixVersionField (C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\fixer.js:191:13)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:32:38
4 verbose stack     at Array.forEach (<anonymous>)
4 verbose stack     at normalize (C:\Program Files\nodejs\node_modules\npm\node_modules\normalize-package-data\lib\normalize.js:31:15)
4 verbose stack     at final (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:411:5)
4 verbose stack     at then (C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:160:5)
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:280:12
4 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:90:16
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
5 verbose cwd D:\antSword
6 verbose Windows_NT 10.0.17134
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
8 verbose node v10.16.2
9 verbose npm  v6.9.0
10 error Invalid version: "2.1.4.1"
11 verbose exit [ 1, true ]
