### ISSUE TITLE
Chunk模式下无法从服务器下载文件

### ISSUE THREAD

**Issue by c2xusnpq6** [AntSwordProject/antSword#272]
```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:572:17)
    at ClientRequest.write (_http_outgoing.js:567:10)
    at Request.write (D:\abc\Documents\antSword-2.1.9\node_modules\superagent\lib\node\index.js:332:14)
    at AntRead.ondata (_stream_readable.js:666:20)
    at AntRead.emit (events.js:182:13)
    at AntRead.Readable.read (_stream_readable.js:486:10)
    at flow (_stream_readable.js:922:34)
    at resume_ (_stream_readable.js:904:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

[确定]
```

**Comment by Medicean** [comment]
提供一下详情复现过程

**Comment by c2xusnpq6** [comment]
[webshell.zip](https://github.com/AntSwordProject/antSword/files/6066352/webshell.zip)
