### ISSUE TITLE
Mime 库大小写导致 Ubuntu、Kali 下载入报错

### ISSUE THREAD

**Issue by atomxw** [AntSwordProject/antSword#318]
ubuntu、kali下载入报错，很多js不兼容。

**Comment by yzddmr6** [comment]
1. 贴一下报错详情
2. 按照文档的安装方式，不要npm install

**Comment by ppofp** [comment]
A JavaScript error occurred in the main
process
Uncaught Exception
Error: Cannot find module
at Module . _ resolueFilenane ( internal / nodules / c j s /
loader.js:584:15)
at Function. Module. resolueFilename(/AntSword-Loader-u4.0.3-linux-x64/
resources/electron.asar/connon/reset-search-paths.js:43:12)
at Function. Module. load(internal/nodules/cjs/
loader.js:510:25)
at Hodule.require(internal/nodules/cjs/loader.js:
640:17)
at require(internal/nodules/cjs/helpers.js:20:18)
at object . <anonynous> (/AntSword-Loader-u4.0.3-linux-x64/antSuord/node_nodules/
mine/index.js:3:12)
at object.<anonynous>(/AntSword-Loader-u4.0.3-linux-x64/antSuord/node_nodules/
mine/index.js:6:3)
pile(internal/nodules/cjs/loader.js:
693:30)Hodule.
at Object . Module . _ extensions . . js ( internal / nodules / c j s /
loader.js:704:10
at Hodule. load(internal/nodules/cjs/loader.js:602:32)

**Comment by atomxw** [comment]
楼上这么仁兄已经贴了，我就不贴了，应该是AntSword-Loader-u4.0.3-linux-x64加载器不兼容[AntSword v2.1.15。

**Comment by atomxw** [comment]
楼上这么仁兄已经贴了，我就不贴了，应该是AntSword-Loader-u4.0.3-linux-x64加载器不兼容[AntSword v2.1.15。

**Comment by Medicean** [comment]
@atomxw @ppofp 已经定位到问题是由于 mime 库自身大小写的问题导致的，可以先这么操作:

```
cd antsword/
mv node_modules/mime/mime.js node_modules/mime/Mime.js
```

**Comment by atomxw** [comment]
其实还有几个问题，设置代理后，打开插件市场无响应，点击蚁剑主界面的“退出程序”，无效果。

**Comment by atomxw** [comment]
点击蚁剑主界面的“x”关闭按钮，无效果。

**Comment by Medicean** [comment]
> 点击蚁剑主界面的“x”关闭按钮，无效果。

这个问题可能是和所用的 electron 版本有关，未来解决，暂时可以右键托盘图标关闭
