### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Jumbo-WJB** [AntSwordProject/antSword#96]
环境：mac
版本：AntSword v2.0.0
启动方式：源码启动、加载器启动、npm start都不行，老版本没问题
报错：
```
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at new Conf (/Users/w/Downloads/antSword/modules/config.js:24:26)
    at Object.<anonymous> (/Users/w/Downloads/antSword/modules/config.js:94:18)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
```

**Comment by Medicean** [comment]
参考最下方：

https://doc.u0u.us/zh-hans/getting_started/get_antsword.html

**Comment by Jumbo-WJB** [comment]
@Medicean  试过了，`启动方式：源码启动、加载器启动、npm start都不行，老版本没问题`里面的源码启动就是这个意思，直接clone下来，然后加载器选择相关目录不可行，也报错

**Comment by Jumbo-WJB** [comment]
![image](https://user-images.githubusercontent.com/7954518/44710124-f03faf80-aadd-11e8-9dae-1723fead378e.png)
是我的权限问题吗

**Comment by Wh0ale** [comment]
我也遇到了   表哥是怎么解决的呀

**Comment by Medicean** [comment]
@Wh0ale 按照文档一步一步走

**Comment by PuPp1T** [comment]
> @Wh0ale 按照文档一步一步走



> 参考最下方：
> 
> https://doc.u0u.us/zh-hans/getting_started/get_antsword.html

文档打不开了哇师傅

**Comment by Medicean** [comment]
> > @Wh0ale 按照文档一步一步走
> 
> > 参考最下方：
> > https://doc.u0u.us/zh-hans/getting_started/get_antsword.html
> 
> 文档打不开了哇师傅

文档已经全面更换为 yuque 

https://www.yuque.com/antswordproject/antsword
